title: Qianjun's Homepage
page-top-title: Qianjun Xia
top-section-bg-text: Mechanical Engineering/Robotics
home-subtitle: Qianjun Xia&ensp;|&ensp;夏乾骏
copyright-text: '&copy; Qianjun Xia 2023-2024. All Rights Reserved.'
