title: Qianjun's Homepage
page-top-title: Qianjun Xia
top-section-bg-text: Mechanical Engineering/Robotics
home-subtitle: Sen Li&ensp;|&ensp;夏乾骏
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
